### ISSUE TITLE
ovirt_storage_connections.py should use NfsVersion not nfs_version

### ISSUE THREAD

**Issue by mgoldboi** [machacekondra/ovirt-ansible-roles#2]
ovirt_storage_connections.py should use NfsVersion

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_S8KC2E/ansible_module_ovirt_storage_connections.py", line 265, in main
    update_params={'force': True},
  File "/tmp/ansible_S8KC2E/ansible_modlib.zip/ansible/module_utils/ovirt.py", line 545, in create
    new_entity = self.build_entity()
  File "/tmp/ansible_S8KC2E/ansible_module_ovirt_storage_connections.py", line 160, in build_entity
    vfs_type=self.param('vfs_type'),
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/types.py", line 8996, in __init__
    self.nfs_version = nfs_version
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/types.py", line 9145, in nfs_version
    Struct._check_type('nfs_version', value, NfsVersion)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/__init__.py", line 110, in _check_type
    expected=expected.__name__,
TypeError: The type 'str' isn't valid for attribute 'nfs_version', it must be 'NfsVersion'

**Comment by machacekondra** [comment]
Fixed by: https://github.com/machacekondra/ovirt-ansible-roles/commit/63f81d20dba82c0be4103de6c80f9de84ed6aaa8
